version: '3'

services:
  db:
    image: postgres
    container_name: db
    # volumes:
      # - /my/own/datadir:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=CGCEnfsEqYG7SpAdXSSU
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  web:
    build: .
    container_name: web
    command: /bin/bash startup.sh
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DB_TYPE=postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=CGCEnfsEqYG7SpAdXSSU
      - DB_HOST=db
      - APP_DEBUG=True
      # - APP_SECRET_KEY=asdlfajsdf;lajksfdj
      - TIMEZONE=America/Chicago